sudo: false
language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
  - '4'
  - 'iojs-v3'
  - 'iojs-v2'
  - 'iojs-v1'
before_install:
  - npm i -g npm@3
before_script:
  - npm prune
script:
  - npm run travis
